/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "../../../utils/useGltf";

export default function Model(props) {
  const group = useRef();
  const { nodes } = useGLTF("/models/antibodies/antibody_poliovirus_10.glb");
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[-21.83, -44.89, -59.32]}>
        <mesh
          material={nodes["1fptcif_H_Gaussian_surface"].material}
          geometry={nodes["1fptcif_H_Gaussian_surface"].geometry}
        />
        <mesh
          material={nodes["1fptcif_L_Gaussian_surface"].material}
          geometry={nodes["1fptcif_L_Gaussian_surface"].geometry}
        />
        <mesh
          material={nodes["1fptcif_P_Gaussian_surface"].material}
          geometry={nodes["1fptcif_P_Gaussian_surface"].geometry}
        />
      </group>
    </group>
  );
}

// useGLTF.preload("/models/antibodies/antibody_poliovirus_10.glb");
