/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "../../../utils/useGltf";

export default function Model(props) {
  const group = useRef();
  const { nodes } = useGLTF(
    "/models/nanotech/six_fold_symmetric_dna_scaffold_10.glb"
  );
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[32.46, -3.13, 16.28]}>
        <mesh
          material={nodes["6dklcif_A_SES_surface"].material}
          geometry={nodes["6dklcif_A_SES_surface"].geometry}
        />
        <mesh
          material={nodes["6dklcif_B_SES_surface"].material}
          geometry={nodes["6dklcif_B_SES_surface"].geometry}
        />
        <mesh
          material={nodes["6dklcif_C_SES_surface"].material}
          geometry={nodes["6dklcif_C_SES_surface"].geometry}
        />
        <mesh
          material={nodes["6dklcif_D_SES_surface"].material}
          geometry={nodes["6dklcif_D_SES_surface"].geometry}
        />
      </group>
    </group>
  );
}

// useGLTF.preload("/models/nanotech/six_fold_symmetric_dna_scaffold_10.glb");
