/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei/useGLTF";

export default function Model(props) {
  const group = useRef();
  const { nodes } = useGLTF("/models/nanotech/tetrahedral_nanoparticle_20.glb");
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[-155.84, -152.84, -145.66]}>
        <mesh
          material={nodes["6vfhcif_assembly_1_A_Gaussian_surface"].material}
          geometry={nodes["6vfhcif_assembly_1_A_Gaussian_surface"].geometry}
        />
        <mesh
          material={nodes["6vfhcif_assembly_1_B_Gaussian_surface"].material}
          geometry={nodes["6vfhcif_assembly_1_B_Gaussian_surface"].geometry}
        />
      </group>
    </group>
  );
}

// useGLTF.preload("/models/nanotech/tetrahedral_nanoparticle_20.glb");
