/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: EnriqueBumbury (https://sketchfab.com/EnriqueBumbury)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/nqo1-holo-form-7e130a567ae742748a5a44774fbb479c
title: NQO1 Holo Form
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei/useGLTF";

export default function Model(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF(
    "/models/nqo1_holo_form/scene.gltf"
  ) as any;
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group
          position={[6.56, -17.13, -25.68]}
          rotation={[1.36, 1.38, -2.66]}
          scale={[1, 1, 1]}
        >
          <mesh
            material={materials.material_0}
            geometry={nodes.mesh_0.geometry}
          />
          <mesh
            material={materials.material_0}
            geometry={nodes.mesh_1.geometry}
          />
          <mesh
            material={materials.material_0}
            geometry={nodes.mesh_2.geometry}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/nqo1_holo_form/scene.gltf");
