/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: MedChemProf (https://sketchfab.com/MedChemProf)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/thrombin-argatroban-complex-85e903249bae4e238652b437412c8b9d
title: Thrombin Argatroban Complex
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei/useGLTF";

export default function Model(props) {
	const group = useRef();
	const { nodes, materials } = useGLTF(
		"/models/thrombin_argatroban_complex/scene.gltf"
	) as any;
	return (
		<group ref={group} {...props} dispose={null}>
			<group rotation={[-Math.PI / 2, 0, 0]}>
				<group rotation={[Math.PI / 2, 0, 0]}>
					<group
						position={[59.19, 23.13, 65.24]}
						rotation={[1.86, -1.32, -1.78]}
						scale={[1, 1, 1]}
					>
						<mesh
							material={materials.material_0}
							geometry={nodes.mesh_0.geometry}
						/>
					</group>
					<group
						position={[59.19, 23.13, 65.24]}
						rotation={[1.86, -1.32, -1.78]}
						scale={[1, 1, 1]}
					>
						<group position={[28.75, 13.51, 25.64]} rotation={[0, 0, 0]}>
							<mesh
								material={materials.material_1}
								geometry={nodes.mesh_1.geometry}
							/>
						</group>
						<group position={[28.55, 13.65, 27.06]} rotation={[0, 0, 0]}>
							<mesh
								material={materials.material_2}
								geometry={nodes.mesh_2.geometry}
							/>
						</group>
						<group position={[27.67, 13.4, 24.68]} rotation={[0, 0, 0]}>
							<mesh
								material={materials.material_3}
								geometry={nodes.mesh_3.geometry}
							/>
						</group>
						<group position={[31.8, 11.76, 28.24]} rotation={[0, 0, 0]}>
							<mesh
								material={materials.material_4}
								geometry={nodes.mesh_4.geometry}
							/>
						</group>
						<group position={[32.86, 10.96, 27.6]} rotation={[0, 0, 0]}>
							<mesh
								material={materials.material_5}
								geometry={nodes.mesh_5.geometry}
							/>
						</group>
						<group position={[32.26, 9.83, 26.84]} rotation={[0, 0, 0]}>
							<mesh
								material={materials.material_6}
								geometry={nodes.mesh_6.geometry}
							/>
						</group>
						<group position={[31.31, 10.36, 25.86]} rotation={[0, 0, 0]}>
							<mesh
								material={materials.material_7}
								geometry={nodes.mesh_7.geometry}
							/>
						</group>
						<group position={[31.06, 9.68, 24.68]} rotation={[0, 0, 0]}>
							<mesh
								material={materials.material_8}
								geometry={nodes.mesh_8.geometry}
							/>
						</group>
						<group position={[30.11, 10.2, 23.8]} rotation={[0, 0, 0]}>
							<mesh
								material={materials.material_9}
								geometry={nodes.mesh_9.geometry}
							/>
						</group>
						<group position={[29.38, 11.36, 24.12]} rotation={[0, 0, 0]}>
							<mesh
								material={materials.material_10}
								geometry={nodes.mesh_10.geometry}
							/>
						</group>
						<group position={[29.56, 11.96, 25.33]} rotation={[0, 0, 0]}>
							<mesh
								material={materials.material_11}
								geometry={nodes.mesh_11.geometry}
							/>
						</group>
						<group position={[30.6, 11.55, 26.22]} rotation={[0, 0, 0]}>
							<mesh
								material={materials.material_12}
								geometry={nodes.mesh_12.geometry}
							/>
						</group>
						<group position={[33.79, 10.42, 28.67]} rotation={[0, 0, 0]}>
							<mesh
								material={materials.material_13}
								geometry={nodes.mesh_13.geometry}
							/>
						</group>
						<group position={[30.83, 12.25, 27.3]} rotation={[0, 0, 0]}>
							<mesh
								material={materials.material_14}
								geometry={nodes.mesh_14.geometry}
							/>
						</group>
						<group position={[29.73, 14.82, 25.18]} rotation={[0, 0, 0]}>
							<mesh
								material={materials.material_15}
								geometry={nodes.mesh_15.geometry}
							/>
						</group>
						<group position={[30.49, 14.83, 23.94]} rotation={[0, 0, 0]}>
							<mesh
								material={materials.material_16}
								geometry={nodes.mesh_16.geometry}
							/>
						</group>
						<group position={[31.83, 14.15, 24.12]} rotation={[0, 0, 0]}>
							<mesh
								material={materials.material_17}
								geometry={nodes.mesh_17.geometry}
							/>
						</group>
						<group position={[32.52, 14.3, 25.11]} rotation={[0, 0, 0]}>
							<mesh
								material={materials.material_18}
								geometry={nodes.mesh_18.geometry}
							/>
						</group>
						<group position={[30.71, 16.24, 23.45]} rotation={[0, 0, 0]}>
							<mesh
								material={materials.material_19}
								geometry={nodes.mesh_19.geometry}
							/>
						</group>
						<group position={[30.91, 17.17, 24.6]} rotation={[0, 0, 0]}>
							<mesh
								material={materials.material_20}
								geometry={nodes.mesh_20.geometry}
							/>
						</group>
						<group position={[31.36, 18.51, 24.01]} rotation={[0, 0, 0]}>
							<mesh
								material={materials.material_21}
								geometry={nodes.mesh_21.geometry}
							/>
						</group>
						<group position={[31.58, 19.5, 25.07]} rotation={[0, 0, 0]}>
							<mesh
								material={materials.material_22}
								geometry={nodes.mesh_22.geometry}
							/>
						</group>
						<group position={[32.84, 19.88, 25.36]} rotation={[0, 0, 0]}>
							<mesh
								material={materials.material_23}
								geometry={nodes.mesh_23.geometry}
							/>
						</group>
						<group position={[33.87, 19.3, 24.69]} rotation={[0, 0, 0]}>
							<mesh
								material={materials.material_24}
								geometry={nodes.mesh_24.geometry}
							/>
						</group>
						<group position={[33.05, 20.7, 26.41]} rotation={[0, 0, 0]}>
							<mesh
								material={materials.material_25}
								geometry={nodes.mesh_25.geometry}
							/>
						</group>
						<group position={[32.34, 13.53, 23.01]} rotation={[0, 0, 0]}>
							<mesh
								material={materials.material_26}
								geometry={nodes.mesh_26.geometry}
							/>
						</group>
						<group position={[31.63, 13.59, 21.74]} rotation={[0, 0, 0]}>
							<mesh
								material={materials.material_27}
								geometry={nodes.mesh_27.geometry}
							/>
						</group>
						<group position={[31.56, 12.21, 21.09]} rotation={[0, 0, 0]}>
							<mesh
								material={materials.material_28}
								geometry={nodes.mesh_28.geometry}
							/>
						</group>
						<group position={[32.93, 11.62, 21.03]} rotation={[0, 0, 0]}>
							<mesh
								material={materials.material_29}
								geometry={nodes.mesh_29.geometry}
							/>
						</group>
						<group position={[33.57, 11.6, 22.41]} rotation={[0, 0, 0]}>
							<mesh
								material={materials.material_30}
								geometry={nodes.mesh_30.geometry}
							/>
						</group>
						<group position={[33.63, 12.93, 23.08]} rotation={[0, 0, 0]}>
							<mesh
								material={materials.material_31}
								geometry={nodes.mesh_31.geometry}
							/>
						</group>
						<group position={[32.24, 14.65, 20.82]} rotation={[0, 0, 0]}>
							<mesh
								material={materials.material_32}
								geometry={nodes.mesh_32.geometry}
							/>
						</group>
						<group position={[31.88, 14.58, 19.65]} rotation={[0, 0, 0]}>
							<mesh
								material={materials.material_33}
								geometry={nodes.mesh_33.geometry}
							/>
						</group>
						<group position={[32.52, 15.72, 21.3]} rotation={[0, 0, 0]}>
							<mesh
								material={materials.material_34}
								geometry={nodes.mesh_34.geometry}
							/>
						</group>
						<group position={[32.8, 10.22, 20.48]} rotation={[0, 0, 0]}>
							<mesh
								material={materials.material_35}
								geometry={nodes.mesh_35.geometry}
							/>
						</group>
						<group
							position={[28.7, 13.55, 26.03]}
							rotation={[1.46, 0.12, 0.14]}
							scale={[1, 1, 1]}
						>
							<mesh
								material={materials.material_36}
								geometry={nodes.mesh_36.geometry}
							/>
						</group>
						<group
							position={[28.6, 13.62, 26.74]}
							rotation={[-1.65, 0.15, -0.14]}
							scale={[1, 1, 1]}
						>
							<mesh
								material={materials.material_37}
								geometry={nodes.mesh_37.geometry}
							/>
						</group>
						<group
							position={[28.45, 13.48, 25.37]}
							rotation={[-0.9, -0.56, 1.08]}
							scale={[1, 1, 1]}
						>
							<mesh
								material={materials.material_38}
								geometry={nodes.mesh_38.geometry}
							/>
						</group>
						<group
							position={[27.91, 13.42, 24.89]}
							rotation={[0.84, -0.47, -1]}
							scale={[1, 1, 1]}
						>
							<mesh
								material={materials.material_39}
								geometry={nodes.mesh_39.geometry}
							/>
						</group>
						<group
							position={[28.96, 13.11, 25.56]}
							rotation={[-0.22, 0.67, -2.52]}
							scale={[1, 1, 1]}
						>
							<mesh
								material={materials.material_40}
								geometry={nodes.mesh_40.geometry}
							/>
						</group>
						<group
							position={[29.37, 12.33, 25.41]}
							rotation={[0.17, 0.04, 0.47]}
							scale={[1, 1, 1]}
						>
							<mesh
								material={materials.material_41}
								geometry={nodes.mesh_41.geometry}
							/>
						</group>
						<group
							position={[29.01, 13.85, 25.52]}
							rotation={[-0.27, 0.09, -0.62]}
							scale={[1, 1, 1]}
						>
							<mesh
								material={materials.material_42}
								geometry={nodes.mesh_42.geometry}
							/>
						</group>
						<group
							position={[29.5, 14.51, 25.29]}
							rotation={[0.37, 0.74, 2.24]}
							scale={[1, 1, 1]}
						>
							<mesh
								material={materials.material_43}
								geometry={nodes.mesh_43.geometry}
							/>
						</group>
						<group
							position={[32.33, 11.36, 27.92]}
							rotation={[-0.63, 0.75, -1.75]}
							scale={[1, 1, 1]}
						>
							<mesh
								material={materials.material_44}
								geometry={nodes.mesh_44.geometry}
							/>
						</group>
						<group
							position={[31.54, 11.89, 27.99]}
							rotation={[-0.77, -0.34, 0.8]}
							scale={[1, 1, 1]}
						>
							<mesh
								material={materials.material_45}
								geometry={nodes.mesh_45.geometry}
							/>
						</group>
						<group
							position={[31.05, 12.13, 27.52]}
							rotation={[1.08, -0.73, -1.14]}
							scale={[1, 1, 1]}
						>
							<mesh
								material={materials.material_46}
								geometry={nodes.mesh_46.geometry}
							/>
						</group>
						<group
							position={[32.56, 10.39, 27.22]}
							rotation={[-1.72, -1.03, 0.9]}
							scale={[1, 1, 1]}
						>
							<mesh
								material={materials.material_47}
								geometry={nodes.mesh_47.geometry}
							/>
						</group>
						<group
							position={[33.33, 10.69, 28.14]}
							rotation={[1.26, -0.73, -0.97]}
							scale={[1, 1, 1]}
						>
							<mesh
								material={materials.material_48}
								geometry={nodes.mesh_48.geometry}
							/>
						</group>
						<group
							position={[31.79, 10.09, 26.35]}
							rotation={[-0.78, -0.32, 0.76]}
							scale={[1, 1, 1]}
						>
							<mesh
								material={materials.material_49}
								geometry={nodes.mesh_49.geometry}
							/>
						</group>
						<group
							position={[31.18, 10.02, 25.27]}
							rotation={[-2.03, -0.31, 0.19]}
							scale={[1, 1, 1]}
						>
							<mesh
								material={materials.material_50}
								geometry={nodes.mesh_50.geometry}
							/>
						</group>
						<group
							position={[30.95, 10.95, 26.04]}
							rotation={[0.25, 0.07, 0.52]}
							scale={[1, 1, 1]}
						>
							<mesh
								material={materials.material_51}
								geometry={nodes.mesh_51.geometry}
							/>
						</group>
						<group
							position={[30.58, 9.94, 24.24]}
							rotation={[-0.72, -0.32, 0.8]}
							scale={[1, 1, 1]}
						>
							<mesh
								material={materials.material_52}
								geometry={nodes.mesh_52.geometry}
							/>
						</group>
						<group
							position={[29.74, 10.78, 23.96]}
							rotation={[0.23, 0.07, 0.55]}
							scale={[1, 1, 1]}
						>
							<mesh
								material={materials.material_53}
								geometry={nodes.mesh_53.geometry}
							/>
						</group>
						<group
							position={[29.47, 11.66, 24.73]}
							rotation={[1.1, -0.08, -0.13]}
							scale={[1, 1, 1]}
						>
							<mesh
								material={materials.material_54}
								geometry={nodes.mesh_54.geometry}
							/>
						</group>
						<group
							position={[30.08, 11.75, 25.78]}
							rotation={[0.94, -0.69, -1.23]}
							scale={[1, 1, 1]}
						>
							<mesh
								material={materials.material_55}
								geometry={nodes.mesh_55.geometry}
							/>
						</group>
						<group
							position={[30.65, 11.72, 26.49]}
							rotation={[0.98, -0.09, -0.18]}
							scale={[1, 1, 1]}
						>
							<mesh
								material={materials.material_56}
								geometry={nodes.mesh_56.geometry}
							/>
						</group>
						<group
							position={[30.77, 12.07, 27.03]}
							rotation={[-2.09, -0.32, 0.19]}
							scale={[1, 1, 1]}
						>
							<mesh
								material={materials.material_57}
								geometry={nodes.mesh_57.geometry}
							/>
						</group>
						<group
							position={[29.91, 14.82, 24.89]}
							rotation={[-1.26, 0.46, -0.62]}
							scale={[1, 1, 1]}
						>
							<mesh
								material={materials.material_58}
								geometry={nodes.mesh_58.geometry}
							/>
						</group>
						<group
							position={[30.29, 14.83, 24.27]}
							rotation={[1.27, 0.47, 0.62]}
							scale={[1, 1, 1]}
						>
							<mesh
								material={materials.material_59}
								geometry={nodes.mesh_59.geometry}
							/>
						</group>
						<group
							position={[31.16, 14.49, 24.03]}
							rotation={[0.12, -0.2, -2.02]}
							scale={[1, 1, 1]}
						>
							<mesh
								material={materials.material_60}
								geometry={nodes.mesh_60.geometry}
							/>
						</group>
						<group
							position={[30.6, 15.54, 23.69]}
							rotation={[-0.33, 0.02, -0.14]}
							scale={[1, 1, 1]}
						>
							<mesh
								material={materials.material_61}
								geometry={nodes.mesh_61.geometry}
							/>
						</group>
						<group
							position={[32.02, 14.19, 24.38]}
							rotation={[1.11, -0.43, -0.67]}
							scale={[1, 1, 1]}
						>
							<mesh
								material={materials.material_62}
								geometry={nodes.mesh_62.geometry}
							/>
						</group>
						<group
							position={[32.36, 14.26, 24.88]}
							rotation={[-1.28, -0.55, 0.73]}
							scale={[1, 1, 1]}
						>
							<mesh
								material={materials.material_63}
								geometry={nodes.mesh_63.geometry}
							/>
						</group>
						<group
							position={[31.96, 14, 23.85]}
							rotation={[-1.82, 0.58, -0.45]}
							scale={[1, 1, 1]}
						>
							<mesh
								material={materials.material_64}
								geometry={nodes.mesh_64.geometry}
							/>
						</group>
						<group
							position={[32.21, 13.69, 23.29]}
							rotation={[0.98, 0.21, 0.38]}
							scale={[1, 1, 1]}
						>
							<mesh
								material={materials.material_65}
								geometry={nodes.mesh_65.geometry}
							/>
						</group>
						<group
							position={[30.81, 16.71, 24.02]}
							rotation={[0.88, -0.06, -0.14]}
							scale={[1, 1, 1]}
						>
							<mesh
								material={materials.material_66}
								geometry={nodes.mesh_66.geometry}
							/>
						</group>
						<group
							position={[31.14, 17.84, 24.3]}
							rotation={[-0.39, 0.06, -0.3]}
							scale={[1, 1, 1]}
						>
							<mesh
								material={materials.material_67}
								geometry={nodes.mesh_67.geometry}
							/>
						</group>
						<group
							position={[31.42, 18.78, 24.29]}
							rotation={[0.81, -0.06, -0.15]}
							scale={[1, 1, 1]}
						>
							<mesh
								material={materials.material_68}
								geometry={nodes.mesh_68.geometry}
							/>
						</group>
						<group
							position={[31.53, 19.27, 24.82]}
							rotation={[-2.27, -0.34, 0.16]}
							scale={[1, 1, 1]}
						>
							<mesh
								material={materials.material_69}
								geometry={nodes.mesh_69.geometry}
							/>
						</group>
						<group
							position={[31.9, 19.6, 25.14]}
							rotation={[0.22, -0.16, -1.24]}
							scale={[1, 1, 1]}
						>
							<mesh
								material={materials.material_70}
								geometry={nodes.mesh_70.geometry}
							/>
						</group>
						<group
							position={[32.53, 19.78, 25.29]}
							rotation={[-0.23, -0.29, 1.8]}
							scale={[1, 1, 1]}
						>
							<mesh
								material={materials.material_71}
								geometry={nodes.mesh_71.geometry}
							/>
						</group>
						<group
							position={[33.09, 19.74, 25.19]}
							rotation={[-0.71, 0.71, -1.57]}
							scale={[1, 1, 1]}
						>
							<mesh
								material={materials.material_72}
								geometry={nodes.mesh_72.geometry}
							/>
						</group>
						<group
							position={[33.61, 19.45, 24.86]}
							rotation={[0.54, 0.27, 0.91]}
							scale={[1, 1, 1]}
						>
							<mesh
								material={materials.material_73}
								geometry={nodes.mesh_73.geometry}
							/>
						</group>
						<group
							position={[32.89, 20.08, 25.62]}
							rotation={[0.89, -0.08, -0.16]}
							scale={[1, 1, 1]}
						>
							<mesh
								material={materials.material_74}
								geometry={nodes.mesh_74.geometry}
							/>
						</group>
						<group
							position={[32.99, 20.49, 26.14]}
							rotation={[-2.19, -0.32, 0.16]}
							scale={[1, 1, 1]}
						>
							<mesh
								material={materials.material_75}
								geometry={nodes.mesh_75.geometry}
							/>
						</group>
						<group
							position={[32.17, 13.55, 22.71]}
							rotation={[-1.27, -0.42, 0.56]}
							scale={[1, 1, 1]}
						>
							<mesh
								material={materials.material_76}
								geometry={nodes.mesh_76.geometry}
							/>
						</group>
						<group
							position={[31.82, 13.58, 22.08]}
							rotation={[1.34, -0.46, -0.57]}
							scale={[1, 1, 1]}
						>
							<mesh
								material={materials.material_77}
								geometry={nodes.mesh_77.geometry}
							/>
						</group>
						<group
							position={[32.64, 13.39, 23.03]}
							rotation={[0.05, -0.08, -2]}
							scale={[1, 1, 1]}
						>
							<mesh
								material={materials.material_78}
								geometry={nodes.mesh_78.geometry}
							/>
						</group>
						<group
							position={[33.28, 13.09, 23.06]}
							rotation={[-0.05, -0.03, 1.13]}
							scale={[1, 1, 1]}
						>
							<mesh
								material={materials.material_79}
								geometry={nodes.mesh_79.geometry}
							/>
						</group>
						<group
							position={[31.6, 12.9, 21.41]}
							rotation={[-2.7, -0.2, 0.05]}
							scale={[1, 1, 1]}
						>
							<mesh
								material={materials.material_80}
								geometry={nodes.mesh_80.geometry}
							/>
						</group>
						<group
							position={[31.94, 14.12, 21.28]}
							rotation={[-0.65, 0.14, -0.42]}
							scale={[1, 1, 1]}
						>
							<mesh
								material={materials.material_81}
								geometry={nodes.mesh_81.geometry}
							/>
						</group>
						<group
							position={[32.25, 11.92, 21.06]}
							rotation={[-0.04, 0.06, -1.97]}
							scale={[1, 1, 1]}
						>
							<mesh
								material={materials.material_82}
								geometry={nodes.mesh_82.geometry}
							/>
						</group>
						<group
							position={[33.25, 11.61, 21.72]}
							rotation={[1.39, -0.4, -0.47]}
							scale={[1, 1, 1]}
						>
							<mesh
								material={materials.material_83}
								geometry={nodes.mesh_83.geometry}
							/>
						</group>
						<group
							position={[32.87, 10.92, 20.76]}
							rotation={[-2.73, -0.45, 0.1]}
							scale={[1, 1, 1]}
						>
							<mesh
								material={materials.material_84}
								geometry={nodes.mesh_84.geometry}
							/>
						</group>
						<group
							position={[33.6, 12.26, 22.74]}
							rotation={[0.47, -0.01, -0.04]}
							scale={[1, 1, 1]}
						>
							<mesh
								material={materials.material_85}
								geometry={nodes.mesh_85.geometry}
							/>
						</group>
						<group
							position={[32.14, 14.63, 20.48]}
							rotation={[-1.54, -0.31, 0.32]}
							scale={[1, 1, 1]}
						>
							<mesh
								material={materials.material_86}
								geometry={nodes.mesh_86.geometry}
							/>
						</group>
						<group
							position={[31.96, 14.59, 19.9]}
							rotation={[1.42, -0.27, -0.31]}
							scale={[1, 1, 1]}
						>
							<mesh
								material={materials.material_87}
								geometry={nodes.mesh_87.geometry}
							/>
						</group>
						<group
							position={[32.32, 14.96, 20.96]}
							rotation={[0.42, -0.05, -0.23]}
							scale={[1, 1, 1]}
						>
							<mesh
								material={materials.material_88}
								geometry={nodes.mesh_88.geometry}
							/>
						</group>
						<group
							position={[32.46, 15.49, 21.2]}
							rotation={[-2.39, -0.94, 0.4]}
							scale={[1, 1, 1]}
						>
							<mesh
								material={materials.material_89}
								geometry={nodes.mesh_89.geometry}
							/>
						</group>
					</group>
				</group>
			</group>
		</group>
	);
}

useGLTF.preload("/scene.gltf");
