/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei/useGLTF";

export default function Model(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/models/other/ATP.glb") as any;
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        material={nodes.ATP___Gaussian_surface.material}
        geometry={nodes.ATP___Gaussian_surface.geometry}
      />
    </group>
  );
}

useGLTF.preload("/models/other/ATP.glb");
