/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/Vault_Shell_80_draco.glb");
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        material={nodes["2qzvcif_assembly_1_A_Gaussian_surface"].material}
        geometry={nodes["2qzvcif_assembly_1_A_Gaussian_surface"].geometry}
      />
      <mesh
        material={nodes["2qzvcif_assembly_1_B_Gaussian_surface"].material}
        geometry={nodes["2qzvcif_assembly_1_B_Gaussian_surface"].geometry}
      />
    </group>
  );
}

// useGLTF.preload('/Vault_Shell_80_draco.glb')
