/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "../../../utils/useGltf";

export default function Model(props) {
  const group = useRef();
  const { nodes } = useGLTF("/models/viruses/denguevirus_50.glb") as any;
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        material={nodes.dengueviruscif_assembly_1_A_Gaussian_surface.material}
        geometry={nodes.dengueviruscif_assembly_1_A_Gaussian_surface.geometry}
      />
      <mesh
        material={nodes.dengueviruscif_assembly_1_B_Gaussian_surface.material}
        geometry={nodes.dengueviruscif_assembly_1_B_Gaussian_surface.geometry}
      />
      <mesh
        material={nodes.dengueviruscif_assembly_1_C_Gaussian_surface.material}
        geometry={nodes.dengueviruscif_assembly_1_C_Gaussian_surface.geometry}
      />
    </group>
  );
}

// useGLTF.preload("/models/viruses/denguevirus_50.glb");
