/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei/useGLTF";

export default function Model(props) {
  const group = useRef();
  const { nodes } = useGLTF("/models/viruses/sindbis_70.glb") as any;
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        material={nodes.Sindbiscif_assembly_1_A_Gaussian_surface.material}
        geometry={nodes.Sindbiscif_assembly_1_A_Gaussian_surface.geometry}
      />
      <mesh
        material={nodes.Sindbiscif_assembly_1_B_Gaussian_surface.material}
        geometry={nodes.Sindbiscif_assembly_1_B_Gaussian_surface.geometry}
      />
      <mesh
        material={nodes.Sindbiscif_assembly_1_C_Gaussian_surface.material}
        geometry={nodes.Sindbiscif_assembly_1_C_Gaussian_surface.geometry}
      />
      <mesh
        material={nodes.Sindbiscif_assembly_1_D_Gaussian_surface.material}
        geometry={nodes.Sindbiscif_assembly_1_D_Gaussian_surface.geometry}
      />
      <mesh
        material={nodes.Sindbiscif_assembly_1_E_Gaussian_surface.material}
        geometry={nodes.Sindbiscif_assembly_1_E_Gaussian_surface.geometry}
      />
      <mesh
        material={nodes.Sindbiscif_assembly_1_F_Gaussian_surface.material}
        geometry={nodes.Sindbiscif_assembly_1_F_Gaussian_surface.geometry}
      />
      <mesh
        material={nodes.Sindbiscif_assembly_1_G_Gaussian_surface.material}
        geometry={nodes.Sindbiscif_assembly_1_G_Gaussian_surface.geometry}
      />
      <mesh
        material={nodes.Sindbiscif_assembly_1_H_Gaussian_surface.material}
        geometry={nodes.Sindbiscif_assembly_1_H_Gaussian_surface.geometry}
      />
      <mesh
        material={nodes.Sindbiscif_assembly_1_I_Gaussian_surface.material}
        geometry={nodes.Sindbiscif_assembly_1_I_Gaussian_surface.geometry}
      />
      <mesh
        material={nodes.Sindbiscif_assembly_1_J_Gaussian_surface.material}
        geometry={nodes.Sindbiscif_assembly_1_J_Gaussian_surface.geometry}
      />
      <mesh
        material={nodes.Sindbiscif_assembly_1_K_Gaussian_surface.material}
        geometry={nodes.Sindbiscif_assembly_1_K_Gaussian_surface.geometry}
      />
      <mesh
        material={nodes.Sindbiscif_assembly_1_L_Gaussian_surface.material}
        geometry={nodes.Sindbiscif_assembly_1_L_Gaussian_surface.geometry}
      />
      <mesh
        material={nodes.Sindbiscif_assembly_1_M_Gaussian_surface.material}
        geometry={nodes.Sindbiscif_assembly_1_M_Gaussian_surface.geometry}
      />
      <mesh
        material={nodes.Sindbiscif_assembly_1_N_Gaussian_surface.material}
        geometry={nodes.Sindbiscif_assembly_1_N_Gaussian_surface.geometry}
      />
      <mesh
        material={nodes.Sindbiscif_assembly_1_O_Gaussian_surface.material}
        geometry={nodes.Sindbiscif_assembly_1_O_Gaussian_surface.geometry}
      />
      <mesh
        material={nodes.Sindbiscif_assembly_1_P_Gaussian_surface.material}
        geometry={nodes.Sindbiscif_assembly_1_P_Gaussian_surface.geometry}
      />
      <mesh
        material={nodes.Sindbiscif_assembly_1_Q_Gaussian_surface.material}
        geometry={nodes.Sindbiscif_assembly_1_Q_Gaussian_surface.geometry}
      />
      <mesh
        material={nodes.Sindbiscif_assembly_1_R_Gaussian_surface.material}
        geometry={nodes.Sindbiscif_assembly_1_R_Gaussian_surface.geometry}
      />
      <mesh
        material={nodes.Sindbiscif_assembly_1_S_Gaussian_surface.material}
        geometry={nodes.Sindbiscif_assembly_1_S_Gaussian_surface.geometry}
      />
      <mesh
        material={nodes.Sindbiscif_assembly_1_T_Gaussian_surface.material}
        geometry={nodes.Sindbiscif_assembly_1_T_Gaussian_surface.geometry}
      />
    </group>
  );
}

// useGLTF.preload("/models/viruses/sindbis_70.glb");
