/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: svtlille (https://sketchfab.com/svtlille)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/models/28db7a6ee32f4e27b1153fe575fe8905
title: ATP
*/

import React, { useRef } from "react";
import { useGLTF } from "../../../utils/useGltf";

export default function Model(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/models/other/ATP.gltf") as any;
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          material={materials["Scene_-_Root"]}
          geometry={nodes.mesh_0.geometry}
        />
      </group>
    </group>
  );
}

// useGLTF.preload("/models/other/ATP.gltf");
