/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei/useGLTF";

export default function Model(props) {
  const group = useRef();
  const { nodes } = useGLTF("/models/other/MlaFEDB_in_nanodiscs_20.glb");
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        material={nodes["6xbd_(1)cif_A_Gaussian_surface"].material}
        geometry={nodes["6xbd_(1)cif_A_Gaussian_surface"].geometry}
      />
      <mesh
        material={nodes["6xbd_(1)cif_B_Gaussian_surface"].material}
        geometry={nodes["6xbd_(1)cif_B_Gaussian_surface"].geometry}
      />
      <mesh
        material={nodes["6xbd_(1)cif_C_Gaussian_surface"].material}
        geometry={nodes["6xbd_(1)cif_C_Gaussian_surface"].geometry}
      />
      <mesh
        material={nodes["6xbd_(1)cif_D_Gaussian_surface"].material}
        geometry={nodes["6xbd_(1)cif_D_Gaussian_surface"].geometry}
      />
      <mesh
        material={nodes["6xbd_(1)cif_E_Gaussian_surface"].material}
        geometry={nodes["6xbd_(1)cif_E_Gaussian_surface"].geometry}
      />
      <mesh
        material={nodes["6xbd_(1)cif_F_Gaussian_surface"].material}
        geometry={nodes["6xbd_(1)cif_F_Gaussian_surface"].geometry}
      />
      <mesh
        material={nodes["6xbd_(1)cif_G_Gaussian_surface"].material}
        geometry={nodes["6xbd_(1)cif_G_Gaussian_surface"].geometry}
      />
      <mesh
        material={nodes["6xbd_(1)cif_H_Gaussian_surface"].material}
        geometry={nodes["6xbd_(1)cif_H_Gaussian_surface"].geometry}
      />
      <mesh
        material={nodes["6xbd_(1)cif_I_Gaussian_surface"].material}
        geometry={nodes["6xbd_(1)cif_I_Gaussian_surface"].geometry}
      />
      <mesh
        material={nodes["6xbd_(1)cif_J_Gaussian_surface"].material}
        geometry={nodes["6xbd_(1)cif_J_Gaussian_surface"].geometry}
      />
      <mesh
        material={nodes["6xbd_(1)cif_K_Gaussian_surface"].material}
        geometry={nodes["6xbd_(1)cif_K_Gaussian_surface"].geometry}
      />
      <mesh
        material={nodes["6xbd_(1)cif_L_Gaussian_surface"].material}
        geometry={nodes["6xbd_(1)cif_L_Gaussian_surface"].geometry}
      />
      <mesh
        material={nodes["6xbd_(1)cif_M_Gaussian_surface"].material}
        geometry={nodes["6xbd_(1)cif_M_Gaussian_surface"].geometry}
      />
      <mesh
        material={nodes["6xbd_(1)cif_N_Gaussian_surface"].material}
        geometry={nodes["6xbd_(1)cif_N_Gaussian_surface"].geometry}
      />
    </group>
  );
}

// useGLTF.preload('/models/other/MlaFEDB_in_nanodiscs_20.glb')
