/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei/useGLTF";

export default function Model(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/models/cells/eosinophil.glb") as any;
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        // material={materials.Material}
        // geometry={nodes.Quad_Sphere.geometry}
        position={[-0.58, -0.3, 0]}
        rotation={[-0.39, 0, 0.54]}
      >
        <meshBasicMaterial />
        <sphereGeometry />
      </mesh>
      <mesh
        // material={materials["Material.001"]}
        // geometry={nodes.Icosphere.geometry}
        position={[0.31, 0.41, 0]}
        scale={[4.61, 4.61, 4.61]}
      >
        <sphereGeometry />
        <meshBasicMaterial />
      </mesh>
    </group>
  );
}

// useGLTF.preload("/models/cells/eosinophil.glb");
