/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "../../../utils/useGltf";

export default function Model(props) {
  const group = useRef();
  const { nodes } = useGLTF(
    "/models/nanotech/computationally_designed_mini_tetraloop_tetraloop_receptor_10_draco.glb"
  );
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        material={nodes["6dvkcif_H_SES_surface"].material}
        geometry={nodes["6dvkcif_H_SES_surface"].geometry}
      />
    </group>
  );
}

// useGLTF.preload( "/models/nanotech/computationally_designed_mini_tetraloop_tetraloop_receptor_10_draco.glb" );
