/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF(
    "/models/nanotech/dna_origami_object_80_cleaned_draco.glb"
  );
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes["4v5xcif_A0_SES_surface"].geometry}
        material={materials["default"]}
      />
    </group>
  );
}

useGLTF.preload("/models/nanotech/dna_origami_object_80_cleaned_draco.glb");
