/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "../../../utils/useGltf";

export default function Model(props) {
  const group = useRef();
  const { nodes } = useGLTF(
    "/models/nanotech/self_assembling_dna_crystal_scaffold_with_rhombohedral_symmetry_6_draco.glb"
  );
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[-85.31, -103.05, 18.21]}>
        <mesh
          material={nodes["6u40cif_A_Gaussian_surface"].material}
          geometry={nodes["6u40cif_A_Gaussian_surface"].geometry}
        />
        <mesh
          material={nodes["6u40cif_B_Gaussian_surface"].material}
          geometry={nodes["6u40cif_B_Gaussian_surface"].geometry}
        />
        <mesh
          material={nodes["6u40cif_C_Gaussian_surface"].material}
          geometry={nodes["6u40cif_C_Gaussian_surface"].geometry}
        />
        <mesh
          material={nodes["6u40cif_D_Gaussian_surface"].material}
          geometry={nodes["6u40cif_D_Gaussian_surface"].geometry}
        />
      </group>
    </group>
  );
}

// useGLTF.preload(
//   "/models/nanotech/self_assembling_dna_crystal_scaffold_with_rhombohedral_symmetry_6_draco.glb"
// );
