/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei/useGLTF";

export default function Model(props) {
  const group = useRef();
  const { nodes } = useGLTF(
    "/models/nanotech/self_assembled_3d_dna_crystals_13_draco.glb"
  );
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        material={nodes["5w6wcif_assembly_1_A_SES_surface"].material}
        geometry={nodes["5w6wcif_assembly_1_A_SES_surface"].geometry}
      />
      <mesh
        material={nodes["5w6wcif_assembly_1_B_SES_surface"].material}
        geometry={nodes["5w6wcif_assembly_1_B_SES_surface"].geometry}
      />
      <mesh
        material={nodes["5w6wcif_assembly_1_C_SES_surface"].material}
        geometry={nodes["5w6wcif_assembly_1_C_SES_surface"].geometry}
      />
      <mesh
        material={nodes["5w6wcif_assembly_1_D_SES_surface"].material}
        geometry={nodes["5w6wcif_assembly_1_D_SES_surface"].geometry}
      />
    </group>
  );
}

// useGLTF.preload("/models/nanotech/self_assembled_3d_dna_crystals_13_draco.glb");
