/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "../../../utils/useGltf";

export default function Model(props) {
  const group = useRef();
  const { nodes } = useGLTF(
    "/models/viruses/adenovirus_160_outer_draco.glb"
  ) as any;

  return (
    <group ref={group} {...props} dispose={null}>
      {Object.values(nodes).map(({ material, geometry }, idx) =>
        idx % 2 === 0 ? <mesh key={idx} {...{ material, geometry }} /> : null
      )}
    </group>
  );
}

// useGLTF.preload("/models/viruses/adenovirus_160_outer_draco.glb");
