/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF(
    "/models/viruses/bacteriophage_phi29_prohead_80_cleaned_draco.glb"
  );
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes["6qvkcif_9R_Gaussian_surface"].geometry}
        material={materials["default"]}
      />
    </group>
  );
}

// useGLTF.preload(
//   "/models/viruses/bacteriophage_phi29_prohead_80_cleaned_draco.glb"
// );
