/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF(
    "/models/viruses/Herpes_600_cleaned_draco.glb"
  );
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes["6q1fcif_assembly_1_z_Gaussian_surface"].geometry}
        material={materials["default"]}
      />
    </group>
  );
}

useGLTF.preload("/models/viruses/Herpes_600_cleaned_draco.glb");
