/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF(
    "/models/viruses/HIV_200_cleaned_draco.glb"
  );
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.HIV.geometry} material={materials["default"]} />
    </group>
  );
}

// useGLTF.preload('/models/viruses/HIV_200_cleaned_draco.glb')
