/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useRef } from "react";
import { useGLTF } from "../../../utils/useGltf";

export default function Model(props) {
  const group = useRef();
  const { nodes } = useGLTF("/models/viruses/HIV_1200_draco.glb");
  return (
    <group ref={group} {...props} dispose={null}>
      {Object.values(nodes).map(({ material, geometry }, idx) =>
        idx % 10 === 0 ? <mesh key={idx} {...{ material, geometry }} /> : null
      )}
    </group>
  );
}

// useGLTF.preload('/models/viruses/HIV_1200_draco.glb')
