/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF(
    "/models/viruses/Rice_dwarf_100_cleaned_draco.glb"
  );
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={
          nodes["Rice_dwarf_Virus_(RDV)cif_assembly_1_B_Gaussian_surface"]
            .geometry
        }
        material={materials["default"]}
      />
    </group>
  );
}

useGLTF.preload("/models/viruses/Rice_dwarf_100_cleaned_draco.glb");
