/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "../../../utils/useGltf";

export default function Model(props) {
  const group = useRef();
  const { nodes } = useGLTF("/models/viruses/varicella_zoster_300_draco.glb");
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[-340.85, -358.3, 290.54]}>
        {Object.values(nodes).map(({ material, geometry }, idx) =>
          idx % 2 === 0 ? <mesh key={idx} {...{ material, geometry }} /> : null
        )}
      </group>
    </group>
  );
}

// useGLTF.preload("/models/viruses/varicella_zoster_300_draco.glb");
