/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "../../../utils/useGltf";

export default function Model(props) {
  const group = useRef();
  const { nodes } = useGLTF(
    "/models/viruses/virion_of_native_gene_transfer_agent_gta_particle_120_draco.glb"
  );
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[-509.07, -512.48, -445.91]}>
        {Object.values(nodes).map(({ material, geometry }, idx) =>
          idx % 1 === 0 ? <mesh key={idx} {...{ material, geometry }} /> : null
        )}
      </group>
    </group>
  );
}

// useGLTF.preload(
//   "/models/viruses/virion_of_native_gene_transfer_agent_gta_particle_120_draco.glb"
// );
