/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Konstantin_Keller (https://sketchfab.com/Konstantin_Keller)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/models/53304c29aa2c41479488f06d3470c796
title: Plasma Membrane
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF(
    "/models/plasma_membrane/scene.gltf"
  ) as any;
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group
          position={[52.9, 26.97, 0.64]}
          rotation={[0, 0.17, -Math.PI]}
          scale={[2.94, 2.94, 2.94]}
        >
          <mesh
            material={materials.protein2}
            geometry={nodes.Sphere004_0?.geometry}
          />
        </group>
        <group
          position={[16.87, 26.89, 0.86]}
          rotation={[0.07, 0.1, -Math.PI]}
          scale={[2.94, 2.94, 2.47]}
        >
          <mesh
            material={materials.protein1}
            geometry={nodes.Torus000_0?.geometry}
          />
        </group>
        <group
          position={[40.8, 17.06, -0.72]}
          rotation={[0.02, -0.07, 3.14]}
          scale={[2.94, 2.94, 2.94]}
        >
          <mesh
            material={materials.protein4}
            geometry={nodes.Sphere002_0?.geometry}
          />
        </group>
        <group
          position={[62.36, 31.91, 0]}
          rotation={[0, 0, -Math.PI]}
          scale={[0.64, 0.64, 0.64]}
        >
          <mesh
            material={materials.lipid}
            geometry={nodes.Icosphere001_0?.geometry}
          />
          <mesh
            material={materials.lipid}
            geometry={nodes.Icosphere001_0_1?.geometry}
          />
          <mesh
            material={materials.lipid}
            geometry={nodes.Icosphere001_0_2?.geometry}
          />
          <mesh
            material={materials.lipid}
            geometry={nodes.Icosphere001_0_3?.geometry}
          />
          <mesh
            material={materials.lipid}
            geometry={nodes.Icosphere001_0_4?.geometry}
          />
          <mesh
            material={materials.lipid}
            geometry={nodes.Icosphere001_0_5?.geometry}
          />
          <mesh
            material={materials.lipid}
            geometry={nodes.Icosphere001_0_6?.geometry}
          />
          <mesh
            material={materials.lipid}
            geometry={nodes.Icosphere001_0_7?.geometry}
          />
          <mesh
            material={materials.lipid}
            geometry={nodes.Icosphere001_0_8?.geometry}
          />
          <mesh
            material={materials.lipid}
            geometry={nodes.Icosphere001_0_9?.geometry}
          />
          <mesh
            material={materials.lipid}
            geometry={nodes.Icosphere001_0_10?.geometry}
          />
          <mesh
            material={materials.lipid}
            geometry={nodes.Icosphere001_0_11?.geometry}
          />
          <mesh
            material={materials.lipid}
            geometry={nodes.Icosphere001_0_12?.geometry}
          />
          <mesh
            material={materials.lipid}
            geometry={nodes.Icosphere001_0_13?.geometry}
          />
          <mesh
            material={materials.lipid}
            geometry={nodes.Icosphere001_0_14?.geometry}
          />
          <mesh
            material={materials.lipid}
            geometry={nodes.Icosphere001_0_15?.geometry}
          />
          <mesh
            material={materials.lipid}
            geometry={nodes.Icosphere001_0_16?.geometry}
          />
          <mesh
            material={materials.lipid}
            geometry={nodes.Icosphere001_0_17?.geometry}
          />
          <mesh
            material={materials.lipid}
            geometry={nodes.Icosphere001_0_18?.geometry}
          />
          <mesh
            material={materials.lipid}
            geometry={nodes.Icosphere001_0_19?.geometry}
          />
          <mesh
            material={materials.lipid}
            geometry={nodes.Icosphere001_0_20?.geometry}
          />
          <mesh
            material={materials.lipid}
            geometry={nodes.Icosphere001_0_21?.geometry}
          />
          <mesh
            material={materials.lipid}
            geometry={nodes.Icosphere001_0_22?.geometry}
          />
          <mesh
            material={materials.lipid}
            geometry={nodes.Icosphere001_0_23?.geometry}
          />
          <mesh
            material={materials.lipid}
            geometry={nodes.Icosphere001_0_24?.geometry}
          />
          <mesh
            material={materials.lipid}
            geometry={nodes.Icosphere001_0_25?.geometry}
          />
        </group>
        <group
          position={[82.34, -32.72, 58.03]}
          rotation={[0.61, 0.49, -0.97]}
          scale={[1.45, 1.45, 1.45]}
        />
        <group
          position={[3.21, 3.39, 0.21]}
          rotation={[-0.09, 0.06, 3.14]}
          scale={[2.94, 2.94, 2.94]}
        >
          <mesh
            material={materials.protein4}
            geometry={nodes.Sphere003_0?.geometry}
          />
        </group>
        <group
          position={[52.03, -0.37, 0.57]}
          rotation={[-0.14, 0.11, 3.14]}
          scale={[2.94, 2.94, 2.47]}
        >
          <mesh
            material={materials.protein1}
            geometry={nodes.Torus002_0?.geometry}
          />
        </group>
        <group
          position={[24.08, 3.05, 0.44]}
          rotation={[-0.07, 0.14, Math.PI]}
          scale={[2.94, 2.94, 2.94]}
        >
          <mesh
            material={materials.protein2}
            geometry={nodes.Sphere005_0?.geometry}
          />
        </group>
        <group
          position={[0.41, 20.87, 1.91]}
          rotation={[-3.09, 0, -Math.PI]}
          scale={[2.94, 2.94, 2.94]}
        >
          <mesh
            material={materials.protein3}
            geometry={nodes.Sphere006_0?.geometry}
          />
        </group>
        <group
          position={[27.96, 13.84, -0.86]}
          rotation={[3.08, -0.06, -Math.PI]}
          scale={[2.94, 2.94, 2.94]}
        >
          <mesh
            material={materials.protein3}
            geometry={nodes.Sphere007_0?.geometry}
          />
        </group>
        <group
          position={[1.09, -6.79, 1.53]}
          rotation={[0, 0.04, 0]}
          scale={[2.94, 2.94, 2.47]}
        >
          <mesh
            material={materials.protein1}
            geometry={nodes.Torus003_0?.geometry}
          />
        </group>
        <group
          position={[20.44, -6.84, 0.58]}
          rotation={[0, 0.1, 0]}
          scale={[2.94, 2.94, 2.94]}
        >
          <mesh
            material={materials.protein2}
            geometry={nodes.Sphere008_0?.geometry}
          />
        </group>
        <group
          position={[37.47, -6.78, 0.07]}
          rotation={[-Math.PI, 0.1, 0]}
          scale={[2.94, 2.94, 2.94]}
        >
          <mesh
            material={materials.protein3}
            geometry={nodes.Sphere009_0?.geometry}
          />
        </group>
        <group
          position={[56.45, -6.81, 0.33]}
          rotation={[0, 0.13, 0]}
          scale={[2.94, 2.94, 2.94]}
        >
          <mesh
            material={materials.protein4}
            geometry={nodes.Sphere010_0?.geometry}
          />
        </group>
      </group>
    </group>
  );
}

// useGLTF.preload("/models/plasma_membrane/scene.gltf");
