/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Vikrama Raghuraman (https://sketchfab.com/vikrama1998)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/lympocyte-f84f96cc9a9847a18e6b469eb2a81fb8
title: Lympocyte
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei/useGLTF";

export default function Model(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/models/cells/lymphocyte.gltf") as any;
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group scale={[2.49, 2.49, 2.49]}>
            <mesh
              material={materials["Material.002"]}
              geometry={nodes.mesh_0.geometry}
            />
            <mesh
              material={materials["Material.002"]}
              geometry={nodes.mesh_1.geometry}
            />
          </group>
          <group position={[0.48, -0.34, 0]} scale={[1.41, 1.41, 1.41]}>
            <mesh
              material={materials["Material.001"]}
              geometry={nodes.mesh_2.geometry}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

// useGLTF.preload("/models/cells/lymphocyte.gltf");
